debug: false
spring:
  jpa:
    show-sql: true
  profiles:
    dev
---
spring:
  profiles:
    neo-production
  datasource:
    jndi-name: java:comp/env/jdbc/DefaultDB
  jpa:
    hibernate:
      ddl-auto: update
debug: false
---
spring:
  profiles:
    cf-production
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
debug: false